### ISSUE TITLE
App Crashing on clicking Photo Capture

### ISSUE THREAD

**Issue by chander-60905** [interwap/camera-fp05#1]
when the capture button is clicked app crashes and in logcat shows ...

Process: com.praescient.components.praescientlibrary, PID: 24225
    java.lang.IllegalArgumentException: x must be >= 0
        at android.graphics.Bitmap.checkXYSign(Bitmap.java:413)
        at android.graphics.Bitmap.createBitmap(Bitmap.java:801)
        at com.praescient.components.camera_fp05.CameraFP05$3.onPictureTaken(CameraFP05.java:387)
        at android.hardware.Camera$EventHandler.handleMessage(Camera.java:1278)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:201)
        at android.app.ActivityThread.main(ActivityThread.java:6810)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)
2019-12-28 17:28:14.172 24225-24225/com.praescient.components.praescientlibrary E/MQSEventManagerDelegate: failed to get MQSService.

**Comment by interwap** [comment]
@chander-60905 do you have the correct permissions for the camera in your application as well as storage?

**Comment by chander-60905** [comment]
yes both the permissions are given in setting

**Comment by interwap** [comment]
@chander-60905  did you follow the step by step guide for installation in the repo readme?

**Comment by chander-60905** [comment]
i am now getting the cropped images of 40-60 kb. how can i get the complete raw image of full resolution

**Comment by interwap** [comment]
@chander-60905 the library was designed to capture passport sized photographs (icao standard) on the fpo5 device. If you want the real image, you may have to fork the project and edit some of the code...
